---
image: debian:bookworm-slim

before_script:
  - export LC_ALL=C.UTF-8
  - export DEBIAN_FRONTEND=noninteractive
  - echo Etc/UTC > /etc/timezone
  - echo 'quiet "1";'
        'APT::Install-Recommends "0";'
        'APT::Install-Suggests "0";'
        'Acquire::Retries "20";'
        'APT::Get::Assume-Yes "true";'
        'Dpkg::Use-Pty "0";'
      > /etc/apt/apt.conf.d/99gitlab
  - apt-get update
  - apt-get dist-upgrade


.ansible-template: &ansible-template
  - apt-get install ansible ansible-lint git python3-apt
  # fix [WARNING]: Ansible is being run in a world writable directory
  - chmod -R go-w $CI_PROJECT_DIR
  # vault won't work in CI because the password can't be decrypted
  - sed -i '/vault_password_file/d' ansible.cfg
  - rm group_vars/*/secret.yml
  # readable output from ansible
  - export ANSIBLE_LOAD_CALLBACK_PLUGINS=1
  - export ANSIBLE_STDOUT_CALLBACK=yaml


# jobs ------------------------------------------------------------------------#

ansible-playbook-syntax-check:
  script:
    - *ansible-template
    - tools/lint-ansible-syntax-check

yamllint:
  only:
    changes:
      - ".*.yml"
      - "*.yml"
  script:
    - apt-get install yamllint
    - tools/lint-yamllint
