---
- name: "setup fronters"
  hosts: endpoints

  tasks:

    - assert:
        that:
          - ansible_distribution == "Debian"
          - ansible_distribution_release == "bullseye"

    # TODO: re-enable check for acme certs once migration is complete
    # this is deactivated while we're migrating using the old f-droid.org certs
    #
    #- stat:
    #    path: "{{ item }}"
    #  loop:
    #    - "{{ endpoint_cert_dir }}/cert.pem"
    #    - "{{ endpoint_cert_dir }}/chain.pem"
    #    - "{{ endpoint_cert_dir }}/fullchain.pem"
    #    - "{{ endpoint_cert_dir }}/privkey.pem"
    #  register: pem_file_stats

    #- name: "make sure all certificate files are present on all endpoints"
    #  assert:
    #    that: "{{ item.stat.exists }}"
    #  loop: "{{ pem_file_stats.results }}"

    - name: "configure nginx"
      block:
        - name: "deploy nginx https site config"
          template:
            src: site-https.j2
            dest: "/etc/nginx/sites-available/https"
            validate: "bash -c 'nginx -t # %s'"
          notify: nginx_reload
        - name: "nginx : enable https site config"
          file:
            src: "/etc/nginx/sites-available/https"
            dest: "/etc/nginx/sites-enabled/https"
            state: link

  handlers:
    - name: nginx_reload
      service:
        name: nginx
        state: reloaded
