---
- name: "setup fronters"
  hosts: endpoints

  tasks:

    - assert:
        that: ansible_distribution_name == "debian"
        that: ansible_distribution_release == "bullseye"

    - stat:
        path: "{{ item }}"
      loop:
        - "{{ endpoint_cert_dir }}/cert.pem"
        - "{{ endpoint_cert_dir }}/chain.pem"
        - "{{ endpoint_cert_dir }}/fullchain.pem"
        - "{{ endpoint_cert_dir }}/privkey.pem"
      register: pem_file_stats

    - name: "make sure all certificate files are present on all endpoints"
      assert:
        that: "{{ item.stat.exists }}"
      loop: "{{ pem_file_stats.results }}"

    - name: "blockinfile: nginx.conf customization"
      blockinfile:
        path: "/etc/nginx/nginx.conf"
        insertafter: 'http {'
        marker: "## {mark} ANSIBLE MANAGED BLOCK"
        content: |
          proxy_cache_path  /var/cache/nginx  levels=1:2  keys_zone=STATIC:10m  inactive=24h  max_size=1g;
          # geoip_country /usr/share/GeoIP/GeoIPv6.dat;
          # log_format privacy '0.0.0.0 - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "-" $geoip_country_code';

    - name: "configure nginx"
      block:
        - name: "deploy nginx https site config"
          template:
            src: site-https.j2
            dest: "/etc/nginx/sites-available/https"
          notify: nginx_reload
        - name: "nginx : enable https site config"
          file:
            src: "/etc/nginx/sites-available/https"
            dest: "/etc/nginx/sites-enabled/https"
            state: link
          notify: nginx_reload

  handlers:
    - name: nginx_reload
      service:
        name: nginx
        state: reloaded
