---
- name: "setup metrics aggregation daemon"
  hosts: endpoints

  tasks:

    - assert:
        that:
          - ansible_distribution == "Debian"
          - ansible_distribution_release == "bullseye"

    - name: "blockinfile: configure tor service"
      include_role:
        name: 'fdroid-metrics'
