---
- name: "fdroidFronter"
  hosts: fdroidFronter

  vars:
    webmastermail: 'hostmaster@h4x.at'

  tasks:

    - include_role:
        name: ansible-debian9-certbot
      vars:
        domain: "{{item}}"
        email: "{{webmastermail}}"
        update_via_nginx: yes
      with_items:
        - 'fdroid-fronter.h4x.at'

    - name: "blockinfile: nginx.conf customization"
      blockinfile:
        path: "/etc/nginx/nginx.conf"
        insertafter: 'http {'
        marker: "## {mark} ANSIBLE MANAGED BLOCK"
        content: |
            proxy_cache_path  /var/cache/nginx  levels=1:2  keys_zone=STATIC:10m  inactive=24h  max_size=1g;
            # geoip_country /usr/share/GeoIP/GeoIPv6.dat;
            # log_format privacy '0.0.0.0 - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "-" $geoip_country_code';

    - include_role:
        name: ansible-debian-nginx-site-tls
      vars:
        domain: "fdroid-fronter.h4x.at"
        ssl_cert_path: "/etc/letsencrypt/live/fdroid-fronter.h4x.at/fullchain.pem"
        ssl_key_path: "/etc/letsencrypt/live/fdroid-fronter.h4x.at/privkey.pem"
        config: |

          location / {
            proxy_pass https://f-droid.org/;

            proxy_buffering        on;
            proxy_cache            STATIC;
            proxy_cache_valid      200  1d;
            proxy_cache_use_stale  error timeout invalid_header updating http_500 http_502 http_503 http_504;

            sub_filter "http://f-droid.org" "https://fdroid-fronter.h4x.at";
            sub_filter "https://f-droid.org" "https://fdroid-fronter.h4x.at";
            sub_filter "http:\/\/f-droid.org\/" "https:\/\/fdroid-fronter.h4x.at\/";
            sub_filter "https:\/\/f-droid.org\/" "https:\/\/fdroid-fronter.h4x.at\/";
            sub_filter "http://" "https://";
            sub_filter "http%3A%2F%2Ff-droid.org" "https%3A%2F%2Ffdroid-fronter.h4x.at";
            sub_filter "https%3A%2F%2Ff-droid.org" "https%3A%2F%2Ffdroid-fronter.h4x.at";
            sub_filter_once off;
          }
