---
endpoints:
  hosts:
    fdroidHttp01:
    fdroidHttp02:

certmachine:
  hosts:
    fdroidCertmachine:

onions:
  hosts:
    fdroidOnion01:

link:
  hosts:
    fdroidLink:

origin:
  hosts:
    fdroidOrigin:
