---
endpoints:
  hosts:
    http01.fdroid.net:
    http02.fdroid.net:
    http03.fdroid.net:

certmachine:
  hosts:
    certmachine.f-droid.org:

onions:
  hosts:
    fdroidorg6cooksyluodepej4erfctzk7rrjpjbbr6wx24jh3lqyfwyd.onion:

link:
  hosts:
    fdroid.link:

origin:
  hosts:
    originserver.f-droid.org:
