---
- name: "basic firewall setup"
  hosts:
    - link

  tasks:

    - assert:
        that: "{{ item }}"
      with_items:
        - ansible_distribution == 'Debian'
        - ansible_distribution_release == 'bookworm'

    - name: lock root account password (for preventing other than pubkey-auth logins)
      user: name=root password_lock=yes

    ##
    # hostname
    #

    - name: set hostname
      ansible.builtin.hostname:
        name: fdroidLink
        use: systemd

    ##
    # APT
    #

    - name: "apt: install debian packages for ansible secure apt setup"
      apt:
        install_recommends: no
        update_cache: yes
        name:
          - iptables-persistent
          - unattended-upgrades
        state: present
        cache_valid_time: 8640000  # ommit cache update when chache has been updated in the last 100 days

    ##
    # install and configure some basic tools
    #

    - name: install some basic tools
      apt:
        install_recommends: no
        state: present
        name:
          - vim
    - name: setup basic vimrc
      copy:
        dest: /root/.vimrc
        content: |
          syntax on
          set mouse-=a
        owner: root
        group: root
        mode: 0644

    ##
    # SSH
    #

    - name: "sshd - require public key authentication, disallow password auth"
      lineinfile:
          path: '/etc/ssh/sshd_config'
          regexp: '^[\s#]*PasswordAuthentication .*'
          line: 'PasswordAuthentication no'
      notify: reload_sshd

    - name: "sshd - require public key authentication, disallow password auth"
      lineinfile:
          path: '/etc/ssh/sshd_config'
          regexp: '^[\s#]*PermitRootLogin .*'
          line: 'PermitRootLogin prohibit-password'
      notify: reload_sshd

    ##
    # firewall
    #

    - name: "deploy persistent ipv4 iptables firewall rules"
      copy:
        dest: /etc/iptables/rules.v4
        content: |
            *filter
            :INPUT DROP [0:0]
            :FORWARD ACCEPT [0:0]
            :OUTPUT ACCEPT [0:0]
            -A INPUT -i lo -j ACCEPT
            -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
            -A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
            -A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
            -A INPUT -p tcp -m tcp --dport 443 -j ACCEPT
            -A INPUT -p icmp --icmp-type 8 -j ACCEPT
            COMMIT
      notify: reload_iptables
    - name: "deploy persistent ipv6 iptables firewall rules"
      copy:
        dest: /etc/iptables/rules.v6
        content: |
            *filter
            :INPUT DROP [0:0]
            :FORWARD ACCEPT [0:0]
            :OUTPUT ACCEPT [0:0]
            -A INPUT -i lo -j ACCEPT
            -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
            -A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
            -A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
            -A INPUT -p tcp -m tcp --dport 443 -j ACCEPT
            -A INPUT -p icmpv6 -j ACCEPT
            COMMIT
      notify: reload_iptables

  handlers:
  - name: reload_iptables
    systemd:
      name: netfilter-persistent.service
      state: restarted
  - name: reload_sshd
    systemd:
      name: sshd.service
      state: reloaded
