# SPDX-FileCopyrightText: 2020 Michael Pöhn <michael.poehn@fsfe.org>
# SPDX-License-Identifier: GPL-3.0-or-later

---

- name: "deploy F-Droid monitor"
  hosts: monitor.f-droid.org

  tasks:

    - name: "fdroid-monitor user"
      user:
        name: fdroid-monitor
        # group: fdroid-monitor
    - apt:
        pkg:
          - git
          - tor
          - python3-humanize
          - python3-pycurl
          - python3-tornado
    - service:
        name: tor
        state: started
        enabled: true
    - git:
        repo: 'https://gitlab.com/fdroid/fdroid-monitor.git'
        dest: '/srv/fdroid-monitor'
        version: '25305801b1f644990b7de6f2a0b556974914ea1a'  # v0.7.1
      notify:
        - restart_service
    - copy:
        dest: '/etc/systemd/system/fdroid-monitor.service'
        content: |
          [Unit]
          Description=F-Droid Monitor Web-App
          AssertPathExists=/srv/fdroid-monitor

          [Service]
          Restart=always
          User=fdroid-monitor
          WorkingDirectory=/srv/fdroid-monitor
          ExecStart=python3 -m fdroidmonitor

          [Install]
          WantedBy=default.target
      notify:
        - systemd_reload_daemon
        - restart_service
    - systemd:
        name: fdroid-monitor.service
        enabled: true

  handlers:
    - name: systemd_reload_daemon
      systemd:
        daemon_reload: true
    - name: restart_service
      systemd:
        name: fdroid-monitor.service
        state: restarted
