# SPDX-FileCopyrightText: 2020 Michael Pöhn <michael.poehn@fsfe.org>
# SPDX-License-Identifier: GPL-3.0-or-later

---

- name: "deploy F-Droid monitor"
  hosts: monitor.f-droid.org
  vars_files:
    - group_vars/all/secret.yml

  tasks:

    - name: "fdroid-monitor user"
      user:
        name: fdroid-monitor
        # group: fdroid-monitor
    - apt:
        pkg:
          - git
          - tor
          - python3-humanize
          - python3-matrix-nio
          - python3-pycurl
          - python3-tornado
    - service:
        name: tor
        state: started
        enabled: true
    - git:
        repo: 'https://gitlab.com/fdroid/fdroid-monitor.git'
        dest: '/srv/fdroid-monitor'
        version: '559b1b14d229684f706faf90ceab987175ba2ef7'  # v0.8.2
      notify:
        - restart_service
    - copy:
        dest: '/etc/systemd/system/fdroid-monitor.service'
        content: |
          [Unit]
          Description=F-Droid Monitor Web-App
          AssertPathExists=/srv/fdroid-monitor

          [Service]
          Restart=always
          User=fdroid-monitor
          WorkingDirectory=/srv/fdroid-monitor
          ExecStart=python3 -m fdroidmonitor

          [Install]
          WantedBy=default.target
      notify:
        - systemd_reload_daemon
        - restart_service
    - file:
        path: /etc/fdroid-monitor
        state: directory
        owner: fdroid-monitor
        mode: 0600
    - copy:
        dest: /etc/fdroid-monitor/fmcfg.ini
        content: "{{ monitor_cfg }}"
        owner: fdroid-monitor
        mode: 0400
      notify:
        - restart_service
    - systemd:
        name: fdroid-monitor.service
        enabled: true

  handlers:
    - name: systemd_reload_daemon
      systemd:
        daemon_reload: true
    - name: restart_service
      systemd:
        name: fdroid-monitor.service
        state: restarted
