# SPDX-FileCopyrightText: 2020 Michael Pöhn <michael.poehn@fsfe.org>
# SPDX-License-Identifier: GPL-3.0-or-later

---

- name: "deploy webserver for monitor.f-droid.org"
  hosts: monitor.f-droid.org

  tasks:

    - name: "apt: enable unattended upgrades"
      apt: "name={{item}} install_recommends=no state=latest"
      with_items:
        - unattended-upgrades
        - libnginx-mod-http-geoip
        - geoip-database

    #######################################################
    # webserver setup for monitor.f-droid.org

    - name: "include_role: get lets encrypt certificate via certbot"
      include_role:
        name: ansible-debian9-certbot
      vars:
        domain: 'monitor.f-droid.org'
        email: 'team@f-droid.org'
        update_via_nginx: yes

    - name: "include_role: configure nginx reverse proxy"
      include_role:
        name: ansible-debian9-nginx-site-tls
      vars:
        domain: "monitor.f-droid.org"
        ssl_cert_path: "/etc/letsencrypt/live/monitor.f-droid.org/fullchain.pem"
        ssl_key_path: "/etc/letsencrypt/live/monitor.f-droid.org/privkey.pem"
        config: |
          add_header  Strict-Transport-Security max-age=63072000;
          add_header  Content-Security-Policy   "default-src 'none'; img-src https:; script-src 'self'; style-src 'self' 'unsafe-inline'; font-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'";
          add_header  X-XSS-Protection          "1; mode=block";
          add_header  X-Content-Type-Options    nosniff;
          add_header  X-Frame-Options           DENY;
          add_header  Referrer-Policy           no-referrer;
          add_header  Permissions-Policy        interest-cohort=();
          location / {
            proxy_pass http://127.0.0.1:8986;
            # proxy_buffering        on;
            # proxy_cache            STATIC;
            # proxy_cache_valid      200  1m;
            # proxy_cache_use_stale  error timeout invalid_header updating http_500 http_502 http_503 http_504;
            # root /nonexistent;
          }

    - name: "blockinfile: nginx.conf customization"
      blockinfile:
        path: "/etc/nginx/nginx.conf"
        insertafter: 'http {'
        marker: "## {mark} ANSIBLE MANAGED BLOCK"
        content: |
            proxy_cache_path  /var/cache/nginx  levels=1:2  keys_zone=STATIC:10m  inactive=24h  max_size=1g;
            geoip_country /usr/share/GeoIP/GeoIPv6.dat;
            log_format privacy '0.0.0.0 - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "-" $geoip_country_code';
    - name: "replace: configure privacy freindly nginx access logging"
      replace:
        path: "/etc/nginx/nginx.conf"
        regexp: "access_log .*;"
        replace: "access_log /var/log/nginx/access.log privacy;"
    - name: "replace: turn nginx error logging off"
      replace:
        path: "/etc/nginx/nginx.conf"
        regexp: "error_log .*;"
        replace: "error_log off;"
