---
- name: "setup tor service"
  hosts: onions

  tasks:

    - assert:
        that:
          - ansible_distribution == "Debian"
          - ansible_distribution_release == "bullseye"

    - name: "blockinfile: configure tor service"
      blockinfile:
        path: "/etc/tor/torrc"
        marker: "## {mark} ANSIBLE MANAGED BLOCK"
        content: |
          HiddenServiceDir /var/lib/tor/{{ onion_address }}/
          HiddenServicePort 80 127.0.0.1:80
      notify: tor_reload

  handlers:
    - name: tor_reload
      service:
        name: tor
        state: reloaded
