---

- src: 'https://gitlab.com/fdroid/ansible-role-secure-sshd.git'
  name: 'ansible-role-secure-sshd'
  scm: 'git'
  version: 80bdfc787be42b8dafe64794d6f675708621bc33

- src: 'https://gitlab.com/fdroid/metrics'
  name: 'fdroid-metrics'
  scm: 'git'
  version: 67903355be65aec958f401e3d6db01c7a364c099
